### ISSUE TITLE
Live stream download fails since 7.0.0

### ISSUE THREAD

**Issue by soleny894** [Zibbp/Ceres#7] opened 2022-05-08 19:08 UTC
Hello,

Since my docker images updated to 7.0.0 all my live downloading streaming started to fail. The download is "ok" but when the stream end the encoding with chat fail every time.

Here's what it says:

```
<redacted>_live_chat_render.log
Live chat render <redacted> exited with code null
```

I got no issues with using the 6.0.0 images.

**Comment by Zibbp** [comment] 2022-05-10 14:39
Hi,

I was able to reproduce the issue. I've reverted the version 0.0.7 bump of TwitchDownloader to the previous version. The live chat is downloaded using another method then converted into a format that TwitchDownloader can read to render. I'm assuming the latest TwitchDownloader release slightly changed something.

Release 0.0.8 includes the version downgrade. I've confirmed it is working in 0.0.8 on my side. Please pull that tag or the `:latest` tag and try again.

I'll investigate further and try to put in a fix in the coming days as the latest version of TwitchDownloader has some nice improvements.

**Comment by soleny894** [comment] 2022-05-11 07:31
Hello,

Thanks for the update, I have no live stream up for now but I'll update you if it works again.
Btw, can you add a way to change the "scanning time" for live stream? The current 5 minutes can skip a huge part of the stream beginning.

**Comment by Zibbp** [comment] 2022-05-11 14:30
I can look into allowing that to be customized via an environment variable. One issue having it check quicker than 5 minutes is that Twitch's thumbnails don't update when the stream first starts, it's on a time schedule so you may have broken/default thumbnails.

**Comment by Zibbp** [comment] 2022-05-11 16:55
Hi,

The latest release ([v0.0.9](https://github.com/Zibbp/Ceres/releases/tag/v0.0.9)) allows the cron schedule for checking if channels are live to be set via a Docker environment variable. For more information regarding this feature please check out the [wiki page](https://github.com/Zibbp/Ceres/wiki/Changing-the-Live-Stream-check-cron-job).

**Comment by soleny894** [comment] 2022-05-11 19:16
Hello @Zibbp,

Thanks for adding my suggestion, I'll implement it very soon in my compose file.

About the thumbnail, can't you start checking for thumbnail 5 minutes after the stream start recording? I don't know if it can be implemented like that but separating both can kind of fix this issue? I think nobody mind a neutral thumbnail in their vod list for a few minutes like I always see it on my Twitch following feed when the stream just started.

**Comment by Zibbp** [comment] 2022-05-11 19:55
It's possible. I'll have to find the best approach for doing so. Might be best to do it when the stream ends as I'm already processing the stream then - instead of having to setup a job to run X minutes after a stream starts.

**Comment by Zibbp** [comment] 2022-07-21 15:28
Closing this issue due to the rewrite, Ganymede, being released. Visit the [Ganymede repository](https://github.com/Zibbp/ganymede) for more information.

**Closed as completed by Zibbp** 2022-07-21 15:28 UTC
Labels: bug
